### ISSUE TITLE
lyap_spec

### ISSUE THREAD

**Issue by gazeek** [heggus/Tisean#9]
Thanks for replying to all of the previous issues. I got another one :).

In lyap_spec delay is commented out. Is that on purpose? I mean were there any changes in the making and then the file was abandoned, or was it purposefully ridden of the delay parameter?

**Comment by gazeek** [comment]
And also, why is time (as in execution time) used to determine the output (line 514)?

**Comment by heggus** [comment]
Yes, it is commented out on purpose. For some reason (I don't remember which one :) ) the algorithm does not give the correct lyapuonv exponents for a delay other than 1. You can overcome this restriction by creating a delayed data set with the delay program and read this into lyap_spec.

I used the time command since, depending on the system at hand, the program might run really long. Time was the easiest way to get an regular output independent of the system.
